### ISSUE TITLE
GPS Time Offset is Applied to Manually Entered Time

### ISSUE THREAD

**Issue by robrobinette** [OpenRTX/OpenRTX#130]
I set the local time in my UV380 and it displayed correctly. I then set the GPS time offset to -4 for Eastern Daylight Savings Time. I left the GPS off and Set time with GPS was also off. The problem is the manually set local time is now 4 hours off. The radio is assuming I set UTC and applied the GPS offset. The GPS offset should not be applied unless the GPS is on and Set Time Using GPS is on.

**Comment by silseva** [comment]
As discussed on discord, you had the time shifted back by four hours because you first set the time when the timezone was zero and then changed the timezone. This is due to a weak design of the UI, which should be changed. We can consider this issue solved and I'm going to open another issue for the UI reorganization.

Thanks!
