### ISSUE TITLE
"For emergency use press any button" screen appears after flashing.

### ISSUE THREAD

**Issue by jasiek** [OpenRTX/OpenRTX#221]
Hey,

I've flashed [v0.3.6](https://github.com/OpenRTX/OpenRTX/releases/download/v0.3.6/openrtx_gd77_v0.3.6.sgl) on a Radiooddity GD-77 device with an existing codeplug - when I power up the radio I see this screen:

![rn_image_picker_lib_temp_852c6e12-30fc-4798-b6f2-5b83159d02ea](https://github.com/OpenRTX/OpenRTX/assets/37550/305c099e-38bb-4adc-8aaa-39a3cf5369e2)

This screen can be bypassed by pressing any button within the first second of the screen appearing. When accessing the battery info screen I see that the voltage gradually grows to 8.1V and battery charge grows to 100% after ~20 seconds.

If this is a problem assessing the battery level accurately (this radio has been in storage for about a year), then perhaps disabling this feature would be a good idea.

**Comment by jasiek** [comment]
The firmware has been flashed using `radio_tool`.

**Comment by silseva** [comment]
It seems to be an issue with the measurement of battery voltage at startup, with the ADC returning 0V on the first acquisition. Successive readings are ok and thus you see the voltage going up.

**Comment by jasiek** [comment]
Indeed, there is a problem that this screen seems to lock up the radio. If I don't press a button within the first second, the radio becomes frozen.

**Comment by silseva** [comment]
Also the DM-1801 is affected. It seems that these radios have an hardware low-pass filter on the battery voltage probe, which causes the measured voltage to increase a bit slowly since the power up. The digital low-pass filter in the state update function further exacerbates this effect causing the low battery alarm to kick in unconditionally.

Problem has been fixed with commit  c4b7b7a
